name: Test

on:
  pull_request:
    types: [opened, closed, merged]
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: echo "We are testing the action"
      - run: echo "${{github.event.pull_request}}"
